antena/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('registrar/', views.register.as_view(), name='registrar')
]

antena/antena/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('gtec.urls', namespace='gtec')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('account/', include('django.contrib.auth.urls')),
]

antena/gtec/urls.py
from django.urls import path
from gtec.views import IndexTemplateView, VagaListView, VagaUpdateView, VagaCreateView, VagaDeleteView, ClienteCreateView, \
ClienteListView, ClienteUpdateView, ClienteDeleteView, ReservaCreateView, ReservaListView, ReservaUpdateView, ReservaDeleteView

app_name = 'gtec'

urlpatterns = [
	path('', IndexTemplateView.as_view(), name="index"),

	path('vagas/criar/', VagaCreateView.as_view(), name="cadastra_vaga"),

    path('vagas/', VagaListView.as_view(), name="lista_vaga"),

    path('vagas/<pk>', VagaUpdateView.as_view(), name="atualiza_vaga"),

    path('vagas/excluir/<pk>/', VagaDeleteView.as_view(), name="deleta_vaga"),

    path('clientes/criar/', ClienteCreateView.as_view(), name="cria_cliente"),

    path('clientes/', ClienteListView.as_view(), name="lista_cliente"),

    path('clientes/<pk>', ClienteUpdateView.as_view(), name="atualiza_cliente"),

    path('clientes/excluir/<pk>/', ClienteDeleteView.as_view(), name="deleta_cliente"),

    path('reserva/criar/', ReservaCreateView.as_view(), name="cria_reserva"),

    path('reserva/', ReservaListView.as_view(), name="lista_reserva"),

    path('reserva/<pk>', ReservaUpdateView.as_view(), name="atualiza_reserva"),

    path('reserva/excluir/<pk>/', ReservaDeleteView.as_view(), name="deleta_reserva"),

]

antena/account/models.py
from django.db import models

# Create your models here.

antena/gtec/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
import uuid

class Vaga(models.Model):
    id = models.IntegerField('ID', primary_key = True, help_text= 'ID único para essa vaga') # editable = False 'esconde' o campo do id, evitando que ele seja editado
    hora_dev = models.DateField('Hora de Devolução', null = True, blank = True)

    STATUS_VAGA = (
        ('o', 'Ocupada'),
        ('d', 'Desocupada'),
    )

    status = models.CharField(
        max_length = 1,
        choices = STATUS_VAGA,
        blank = True,
        default = 'd',
        help_text = 'Disponibilidade da vaga'
    )

    class Meta:
        verbose_name = "Vaga"
        verbose_name_plural = 'Vaga'
        ordering = ['id'] # Como vão ser ordenadas as vagas. Tentar ordenar pelo status depois!

    def __str__(self):
        return str(self.id)

class Cliente(models.Model):
    nome = models.CharField("Nome", max_length = 50)
    sobrenome = models.CharField("Sobrenome", max_length = 80)
    cpf = models.CharField("CPF", help_text="Digite apenas números", max_length=12)
    telefone = PhoneNumberField("Telefone", max_length = 14, null=False, blank=False, unique=True)
    email = models.EmailField("E-mail", blank=True, unique=True)
    creditos = models.DecimalField("Créditos", max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Cliente"

    def __str__(self):
        return self.nome

class Reserva(models.Model):
    nome_pessoa = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    cpf = models.CharField("CPF", help_text="Digite apenas numeros", max_length=12, blank=True)
    valor = models.CharField("Valor da vaga", max_length=30, null=True)
    hora_operacao = models.DateTimeField("Hora da operação", null=True)
    hora_prevista_saida = models.DateTimeField("Hora prevista para saída", null=True)
    debito_id = models.UUIDField(default=uuid.uuid4) #não pode ter mais uma primary key
    id_vaga = models.UUIDField(primary_key=True, default=uuid.uuid4)
    hora_saida = models.DateTimeField("Hora da saída", null=True)

    class Meta:
        verbose_name = "Reserva de vagas"
        verbose_name_plural = "Reserva de vagas"

    def __str__(self):
        return ("Reserva do " + self.nome_pessoa.nome)

antena/gtec/forms.py
from django import forms
from .models import Post, Vaga, Cliente, Reserva

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'body', 'author', 'status']

class InsereVagaForm(forms.ModelForm):
	class Meta:
		model = Vaga
		fields = ['id', 'hora_dev', 'status']

class InsereClienteForm(forms.ModelForm):
	class Meta:
		model = Cliente
		fields = ['nome', 'sobrenome', 'cpf', 'telefone', 'email', 'creditos']

class InsereReservaForm(forms.ModelForm):
	class Meta:
		model = Reserva
		fields = ['nome_pessoa', 'cpf', 'valor', 'hora_operacao', 'hora_prevista_saida', 'debito_id', 'id_vaga', 'hora_saida']

class VagaCreate(forms.ModelForm):
    class Meta:
        model = Vaga
        fields = '__all__'

antena/account/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import TemplateView
from braces.views import LoginRequiredMixin

class register(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'account/register.html'

antena/gtec/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.views import generic
from django.urls import reverse_lazy
from .models import Vaga, Cliente, Reserva
from .forms import InsereVagaForm, InsereClienteForm, InsereReservaForm, VagaCreate

class IndexTemplateView(TemplateView):
    template_name = "gtec/index.html"

# VAGAS
class VagaListView(ListView):
    template_name = "gtec/lista.html"
    model = Vaga
    context_object_name = "vaga"

@method_decorator(login_required, name='dispatch')
class VagaCreateView(CreateView):
    template_name = "gtec/cria.html"
    model = Vaga
    form_class = InsereVagaForm
    success_url = reverse_lazy("gtec:lista_vaga")

@method_decorator(login_required, name='dispatch')
class VagaUpdateView(UpdateView):
    template_name = "gtec/atualiza.html"
    model = Vaga
    fields = '__all__'
    context_object_name = 'vaga'
    success_url = reverse_lazy("gtec:lista_vaga")

@method_decorator(login_required, name='dispatch')
class VagaDeleteView(DeleteView):
    template_name = "gtec/exclui.html"
    model = Vaga
    context_object_name = 'vaga'
    success_url = reverse_lazy("gtec:lista_vaga")

# CLIENTES
class ClienteListView(ListView):
    template_name = "gtec/lista_cliente.html"
    model = Cliente
    context_object_name = "cliente"

class ClienteCreateView(CreateView):
    template_name = "gtec/cria_cliente.html"
    model = Cliente
    form_class = InsereClienteForm
    success_url = reverse_lazy("gtec:lista_cliente")

@method_decorator(login_required, name='dispatch')
class ClienteUpdateView(UpdateView):
    template_name = "gtec/atualiza_cliente.html"
    model = Cliente
    fields = '__all__'
    context_object_name = 'cliente'
    success_url = reverse_lazy("gtec:lista_cliente")

@method_decorator(login_required, name='dispatch')
class ClienteDeleteView(DeleteView):
    template_name = "gtec/exclui_cliente.html"
    model = Cliente
    context_object_name = 'cliente'
    success_url = reverse_lazy("gtec:lista_cliente")

# RESERVA DE VAGAS
class ReservaListView(ListView):
    template_name = "gtec/lista_reserva.html"
    model = Reserva
    context_object_name = "reserva"

@method_decorator(login_required, name='dispatch')
class ReservaCreateView(CreateView):
    template_name = "gtec/cria_reserva.html"
    model = Reserva
    form_class = InsereReservaForm
    success_url = reverse_lazy("gtec:lista_reserva")

@method_decorator(login_required, name='dispatch')
class ReservaUpdateView(UpdateView):
    template_name = "gtec/atualiza_reserva.html"
    model = Reserva
    fields = '__all__'
    context_object_name = 'reserva'
    success_url = reverse_lazy("gtec:lista_reserva")

@method_decorator(login_required, name='dispatch')
class ReservaDeleteView(DeleteView):
    template_name = "gtec/exclui_cliente.html"
    model = Reserva
    context_object_name = 'reserva'
    success_url = reverse_lazy("gtec:lista_reserva")

antena/gtec/templates/gtec/about-us.html
{% extends 'gtec/index.html' %}
{% block title %}Título do post{% endblock %}

{% block content %}
	<div class="container">
		<h1>Sobre nós</h1>
		<p>Esta é a história do blog...</p>
	</div>
{% endblock %}

antena/gtec/templates/gtec/atualiza.html
{% extends "gtec/base.html" %}

{% load bootstrap %}

{% load widget_tweaks %}

{% block title %}Atualização de Vaga{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Dados de Vagas</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <div>
                <form action="." method="POST">
                  {% csrf_token %}
                  {{ form|bootstrap }}
                    <hr />
                    <div class="text-right">
                      <a href="{% url 'gtec:lista_vaga' %}" class="btn btn-outline-primary">Voltar</a>
                      <button class="btn btn-primary">Enviar</button>
                    </div>
                </form>
            </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

antena/gtec/templates/gtec/atualiza_cliente.html
{% extends "gtec/base.html" %}

{% load bootstrap %}

{% load widget_tweaks %}

{% block title %}Atualização de Cliente{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Dados de Cliente</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <div>
                <form action="." method="POST">
                  {% csrf_token %}
                  {{ form|bootstrap }}
                    <hr />
                    <div class="text-right">
                      <a href="{% url 'gtec:lista_cliente' %}" class="btn btn-outline-primary">Voltar</a>
                      <button class="btn btn-primary">Enviar</button>
                    </div>
                </form>
            </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

antena/gtec/templates/gtec/atualiza_reserva.html
{% extends "gtec/base.html" %}

{% load bootstrap %}

{% load widget_tweaks %}

{% block title %}Atualização de Reserva{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Dados de Reserva</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <div>
                <form action="." method="POST">
                  {% csrf_token %}
                  {{ form|bootstrap }}
                    <hr />
                    <div class="text-right">
                      <a href="{% url 'gtec:lista_reserva' %}" class="btn btn-outline-primary">Voltar</a>
                      <button class="btn btn-primary">Enviar</button>
                    </div>
                </form>
            </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

antena/gtec/templates/gtec/contact.html
{% extends 'gtec/index.html' %}
{% block title %}Título do post{% endblock %}

{% block content %}
	<div class="container">
		<h1>Quer entrar em contato conosco?</h1>
	</div>
{% endblock %}

antena/gtec/templates/gtec/cria.html
{% extends "gtec/base.html" %}

{% load bootstrap %}
{% load static %}

{% load widget_tweaks %}

{% block title %}Adicionar uma vaga{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Crie uma Vaga</h5>
          <p class="card-text">
            Complete o cadastro abaixo para criar uma nova Vaga.
          </p>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <div>
              <form action="." method="POST">
                  {% csrf_token %}
                  {{ form|bootstrap }}
                  <div class="text-right">
                    <a href="{% url 'gtec:lista_vaga' %}" class="btn btn-outline-primary">Voltar</a>
                    <button class="btn btn-primary">Criar</button>
                  </div>
              </form>
            
            </div>

            <hr>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

antena/gtec/templates/gtec/cria_cliente.html
{% extends "gtec/base.html" %}

{% load bootstrap %}
{% load static %}

{% load widget_tweaks %}

{% block title %}Cadastro no Sistema{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Crie seu Cadastro</h5>
          <p class="card-text">
            Complete o cadastro abaixo para criar uma conta no sistema.
          </p>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <div>
              <form action="." method="POST">
                  {% csrf_token %}
                  {{ form|bootstrap }}
                  <div class="text-right">
                    <a href="{% url 'gtec:lista_cliente' %}" class="btn btn-outline-primary">Voltar</a>
                    <button class="btn btn-primary">Criar</button>
                  </div>
              </form>
            
            </div>

            <hr>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

antena/gtec/templates/gtec/cria_reserva.html
{% extends "gtec/base.html" %}

{% load bootstrap %}
{% load static %}

{% load widget_tweaks %}

{% block title %}Reserva de Vagas{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Faça a reserva</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <div>
              <form action="." method="POST">
                  {% csrf_token %}
                  {{ form|bootstrap }}
                  <div class="text-right">
                    <a href="{% url 'gtec:lista_reserva' %}" class="btn btn-outline-primary">Voltar</a>
                    <button class="btn btn-primary">Criar</button>
                  </div>
              </form>
            
            </div>

            <hr>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

antena/gtec/templates/gtec/exclui.html
{% extends "gtec/base.html" %}

{% load static %}

{% block title %}Página Inicial{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Vagas</h5>

        <p class="card-text">
          Você tem certeza que quer excluir a vaga <b>{{ vaga.id }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'gtec:lista_vaga' %}" class="btn btn-outline-danger">
              Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

antena/gtec/templates/gtec/exclui_reserva.html
{% extends "gtec/base.html" %}

{% load static %}

{% block title %}Página Inicial{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Reserva</h5>

        <p class="card-text">
          Você tem certeza que quer excluir a Reserva <b>{{ reserva.id_vaga }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'gtec:lista_reserva' %}" class="btn btn-outline-danger">
              Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

antena/gtec/templates/gtec/index.html
{% extends "gtec/base.html" %}
{% load static %}
{% load bootstrap %}

{% block content %}
<div class="container-fluid">
		{% if user.is_authenticated %}
			<p class="logged-in-p">
				Olá {{ user.username }} seja bem vindo, o que deseja fazer hoje? 
			</p>
			<div class="container-fluid">
		        <a class="btn btn-primary" href="{% url 'gtec:cadastra_vaga' %}" role="button">Adicionar Vagas</a>
		        <a class="btn btn-primary" href="{% url 'gtec:lista_vaga' %}" role="button">Ver Vagas</a>
		        <a class="btn btn-primary" href="{% url 'gtec:lista_cliente' %}" role="button">Ver Clientes</a>
		        <a class="btn btn-primary" href="{% url 'gtec:cria_reserva' %}" role="button">Reservar Vagas</a>
		    </div>
		{% endif %}
</div>
<br/>
 <div class="container-fluid">
	<div class="jumbotron jumbotron-fluid">
	  <div class="container">
	    <h1 class="display-4">Bem vindo ao SAVAGE!</h1>
	    <p class="lead">Sistema Autônomo de Vagas em Garagens e Estacionamentos</p>
	    <a class="btn btn-primary" href="{% url 'gtec:cria_cliente' %}" role="button">Cadastre-se aqui</a>
	    ou
	    <a class="btn btn-primary" href="{% url 'login' %}" role="button">Faça login</a>
	  </div>
	</div>
</div>

<div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
          </div>

          <!-- Content Row -->
          <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Vagas Totais</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">452</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Investimentos</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">R$21,000</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Retorno</div>
                      <div class="row no-gutters align-items-center">
                        <div class="col-auto">
                          <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                        </div>
                        <div class="col">
                          <div class="progress progress-sm mr-2">
                            <div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Pending Requests Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Empresas Parceiras</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
{% endblock %}

antena/gtec/templates/gtec/lista.html
{% extends 'gtec/base.html' %}

{% load bootstrap %}

{% block title %}Listagem de Vagas{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Listagem de Vagas</h5>

          {% if vaga|length > 0 %}
            <p class="card-text">
              Aqui está a lista de Vagas cadastradas.
            </p>

            <table class="table">
              <thead class="thead">
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Hora Devolução</th>
                <th scope="col">Status</th>
              </tr>
              </thead>
              <tbody>
              {% for vaga in vaga %}
                <tr>
                  <th scope="row">{{ vaga.id }}</th>
                  <td>{{ vaga.hora_dev }}</td>
                  <td>{{ vaga.status }}</td>
                  <td class="text-center">
                    <a href="{% url 'gtec:atualiza_vaga' pk=vaga.id %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'gtec:deleta_vaga' pk=vaga.id %}"
                      class="btn btn-danger">
                      Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhuma vaga cadastrada ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'gtec:cadastra_vaga' %}" class="btn btn-primary">
              Cadastrar Vaga
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

antena/gtec/templates/gtec/lista_cliente.html
{% extends 'gtec/base.html' %}

{% load bootstrap %}

{% block title %}Listagem de Clientes{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Listagem de Clientes</h5>

          {% if cliente|length > 0 %}
            <p class="card-text">
              Aqui está a lista de Clientes cadastrados.
            </p>

            <table class="table">
              <thead class="thead">
              <tr>
                <th scope="col">Nome</th>
                <th scope="col">Sobrenome</th>
                <th scope="col">CPF</th>
                <th scope="col">Telefone</th>
                <th scope="col">Email</th>
                <th scope="col">Crédito</th>
              </tr>
              </thead>
              <tbody>
              {% for cliente in cliente %}
                <tr>
                  <th scope="row">{{ cliente.nome }}</th>
                  <td>{{ cliente.sobrenome }}</td>
                  <td>{{ cliente.cpf }}</td>
                  <th>{{ cliente.telefone }}</th>
                  <td>{{ cliente.email }}</td>
                  <td>{{ cliente.creditos }}</td>
                  <td class="text-center">
                    <a href="{% url 'gtec:atualiza_cliente' pk=cliente.nome %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'gtec:deleta_cliente' pk=cliente.nome %}"
                      class="btn btn-danger">
                      Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum cliente cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'gtec:cria_cliente' %}" class="btn btn-primary">
              Cadastrar Cliente
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

antena/gtec/templates/gtec/lista_reserva.html
{% extends 'gtec/base.html' %}

{% load bootstrap %}

{% block title %}Lista de Reservas{% endblock %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Reservas</h5>

          {% if reserva|length > 0 %}
            <p class="card-text">
              Aqui está a lista de Reservas cadastradas.
            </p>

            <table class="table">
              <thead class="thead">
              <tr>
                <th scope="col">Nome</th>
                <th scope="col">CPF</th>
                <th scope="col">Valor da Vaga</th>
                <th scope="col">Hora da Operação</th>
                <th scope="col">Hora da Saída</th>
                <th scope="col">Débito ID</th>
                <th scope="col">ID da Vaga</th>
                <th scope="col">Hora da Saída</th>
              </tr>
              </thead>
              <tbody>
              {% for reserva in reserva %}
                <tr>
                  <th scope="row">{{ reserva.nome }}</th>
                  <td>{{ reserva.cpf }}</td>
                  <td>{{ reserva.valor }}</td>
                  <th>{{ reserva.hora_operacao }}</th>
                  <td>{{ reserva.hora_prevista_saida }}</td>
                  <td>{{ reserva.debito_id }}</td>
                  <td>{{ reserva.id_vaga }}</td>
                  <td>{{ reserva.hora_saida }}</td>
                  <td class="text-center container-fluid">
                    <a href="{% url 'gtec:atualiza_reserva' pk=reserva.id_vaga %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'gtec:deleta_reserva' pk=reserva.id_vaga %}"
                      class="btn btn-danger">
                      Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhuma reserva feita ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'gtec:cria_reserva' %}" class="btn btn-primary">
              Cadastrar Cliente
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}